# code:language=ansible
---
- name: Worker node check
  tags:
    - never
    - k8s_full_install
    - kubeadm_init
  block:
    - name: Check if node has already joined cluster
      ansible.builtin.stat:
        path: /etc/kubernetes/kubelet.conf
      register: kubelet_conf

    - name: Join worker node to cluster
      ansible.builtin.command: "{{ k8s_join_command }}"
      when:
        - not kubelet_conf.stat.exists
        - k8s_join_command is defined
